import Head from 'next/head';
import { useContext, useState } from 'react';

import { SignInButton } from '../../components/SignInButton';
import { AuthContext } from '../providers/auth';
import styles from './styles/Home.module.css';

export default function Home() {
  const [newTaskEmail, setNewTaskEmail] = useState('');
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [tasks, setTasks] = useState([]);
  function handleCreateTask() {
    if (!newTaskTitle) return;

    const newTask = {
      id: Math.random().toFixed(2),
      title: newTaskTitle,
      email: newTaskEmail,
      isComplete: false,
    };
    setTasks((oldstate) => [...oldstate, newTask]);
    setNewTaskTitle('');
    console.log(newTask);

    localStorage.setItem('user', JSON.stringify(user));
    setUser(input);
  }

  const [input, setInput] = useState({
    name: '',
  });
  const { user, setUser } = useContext(AuthContext);
  console.log(user);

  return (
    <div className={styles.containerHome}>
      <Head>
        <title>X-solar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerFormulario}>
        <form type="text " onSubmit="" action="">
          <label htmlFor="">
            <big>Formulário</big>
          </label>
          <br />
          <label style={{ marginRight: 140 }} className="name" htmlFor="">
            Nome
          </label>
          <br />
          <input
            type="text"
            placeholder="Nome"
            onChange={(e) => setNewTaskTitle(e.target.value)}
            value={newTaskTitle}
          />
          <br />
          <label style={{ marginRight: 140 }} className="email" htmlFor="">
            E-mail
          </label>
          <br />
          <input
            type="text"
            placeholder="Email"
            onChange={(e) => setNewTaskEmail(e.target.value)}
            value={newTaskEmail}
          />
          <SignInButton />
        </form>
        <button onClick={handleCreateTask}>Cadastrar</button>
      </div>
      <main className={styles.mainTabela}>
        <table className={styles.tableContainer1}>
          <thead>
            <tr>
              <th>ID  </th>
              <th>Title </th>
              <th>E-mail  </th>
              
            </tr>
          </thead>

            {tasks.map((task) => (
              <tbody>
                <tr className={styles.tbodyContainer}>
                  <td>{task.id}  </td>
                  <td>{task.title} </td>
                  <td>{task.email}</td>
                  
                </tr>
              </tbody>
            ))}
          
        </table>
      </main>
    </div>
  );
}
