import Head from 'next/head'
import { SignInButton } from '../components/SignInButton'
import styles from './styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.containerHome} >
      <Head>
        <title>X-solar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerFormulario} >
        <form type="text " onSubmit="" action="">
          <label htmlFor=""><big>Formulário</big></label>
          <br/>
          <label className="name" htmlFor="">Nome</label>
          <br/>
          <input  type="text" placeholder="Nome" />
          <br/>
            <label className="email" htmlFor="">E-mail</label>
            <br/>
            <input  type="text" placeholder="Email"/>
            <SignInButton/>

        </form>
      </div>

      

      
    </div>
  )
}
